# Use Python 3.12 UV base image
FROM prefecthq/prefect:3.0.10-python3.12

ENV UV_SYSTEM_PYTHON=1

ARG EXTRA_PIP_PACKAGES

# Set up working directory
WORKDIR /opt/prefect

RUN pip install -U uv
RUN uv pip install $EXTRA_PIP_PACKAGES

# Add your project files
COPY . .
