services:
  server:
    image: prefecthq/prefect:3.1.0-python3.12
    command:
      [
        "prefect",
        "server",
        "start",
        "--host",
        "0.0.0.0"
      ]
    ports:
      - "4200:4200"