services:
  worker:
    image: prefecthq/prefect:2-python3.12
    restart: always
    command:
      [
        "prefect",
        "worker",
        "start",
        "--pool",
        "docker-work",
        "--install-policy",
        "if-not-present"
      ]
    env_file:
      - ../../.env
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
