# Deploys all flows in the src directory to Prefect Cloud

name: Deploy flows

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

on:
  push:
    branches: ["main"]
    paths:
      - src

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_flows:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: zzstoatzz
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Dependencies
        run: |
          pip install .

      - name: Get list of modified python files
        id: getfile
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | tr '\n' ',')
          echo "Modified Python files: $files"
          echo "files=$files" >> $GITHUB_ENV

      - name: Deploy changed flows
        run: |
          entrypoints=$(python ../scripts/get_flow_entrypoints.py)
          echo "Found entrypoints: $entrypoints"
          IFS="," read -ra ENTRYPOINTS <<< "$entrypoints"
          for entrypoint in "${ENTRYPOINTS[@]}"; do
              echo "Deploying flow: $entrypoint"
              prefect --no-prompt deploy $entrypoint
          done

        
