# Deploys all flows in the src directory to Prefect Cloud

name: Deploy flows

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

on:
  push:
    branches: ["main"]
    paths:
      - src

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_flows:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install .

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: zzstoatzz/prefect-monorepo
          username: zzstoatzz
          password: $DOCKERHUB_PASSWORD

      - name: Create or update deployments
        run: |
          prefect --no-prompt deploy --all
