name: Test Prefect Worker on Kubernetes

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_WORK_POOL: kubernetes-pool

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.22.0'

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Prefect Helm Repository
        run: |
          helm repo add prefect https://prefecthq.github.io/prefect-helm
          helm repo update

      - name: Create Namespace
        run: kubectl create namespace prefect

      - name: Create Prefect API Secret
        run: |
          kubectl create secret generic prefect-api-key \
            --namespace=prefect \
            --from-literal=key=$(echo -n $PREFECT_API_KEY | base64)

      - name: Configure values.yaml
        run: |
          PREFECT_ACCOUNT_ID=$(echo $PREFECT_API_URL | cut -d '/' -f 6)
          PREFECT_WORKSPACE_ID=$(echo $PREFECT_API_URL | cut -d '/' -f 8)
          echo "worker:" > values.yaml
          echo "  cloudApiConfig:" >> values.yaml
          echo "    accountId: $PREFECT_ACCOUNT_ID" >> values.yaml
          echo "    workspaceId: $PREFECT_WORKSPACE_ID" >> values.yaml
          echo "  config:" >> values.yaml
          echo "    workPool: $PREFECT_WORK_POOL" >> values.yaml

      - name: Install Prefect Worker
        run: |
          helm install prefect-worker prefect/prefect-worker --namespace=prefect -f values.yaml

      - name: Wait for Pods to Appear and Save Worker Pod Name
        run: |
          for i in {1..3}; do
            kubectl get pods -n prefect
            if [ "$(kubectl get pods -n prefect --no-headers | wc -l)" -gt 0 ]; then
              echo "Pods found!"
              WORKER_POD_NAME=$(kubectl get pods -n prefect --no-headers -o custom-columns=":metadata.name" | grep prefect-worker)
              echo "WORKER_POD_NAME=$WORKER_POD_NAME" >> $GITHUB_ENV
              break
            fi
            echo "No pods found, retrying in 10s..."
            sleep 10
          done

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.12'

      # Cache UV dependencies
      - name: UV Cache
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: uvcache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            uvcache-${{ runner.os }}-

      - name: Install python deps
        run: |
          python -m pip install -U uv
          uv pip install --system git+https://github.com/prefecthq/prefect.git

      - name: Schedule a run and then stream pod logs
        run: |
          prefect deployment run 'random-flow/test-k8s'
          echo "Start tailing logs for $WORKER_POD_NAME"
          kubectl logs -f $WORKER_POD_NAME -n prefect
        
        env:
          WORKER_POD_NAME: ${{ env.WORKER_POD_NAME }}
        
      - name: Delete Kind Cluster
        run: kind delete cluster
