name: Python Compatibility Test

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Optionally install dependencies here, for example:
        # pip install -r requirements.txt

    - name: Run Python files in repros/ (Windows)
      if: runner.os == 'Windows'
      run: |
        for /r repros %f in (*.py) do python "%f"

    - name: Run Python files in repros/ (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        find repros -name '*.py' -exec python {} \;
