name: Prefect Repros on different Python versions and platforms

on:
  workflow_dispatch:

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
  UV_SYSTEM_PYTHON: true

jobs:
  run-repros:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache UV dependencies
      - name: UV Cache
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: uvcache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            uvcache-${{ runner.os }}-

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python files in repros/ (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: >
          for /r "repros" %%f in (*.py) do (
            echo.
            echo ========================================
            echo Running: %%f
            echo ========================================
            uv run "%%f"
          )

      - name: Run Python files in repros/ (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          for file in $(find repros -name '*.py'); do
            echo
            echo "========================================"
            echo "Running: $file"
            echo "========================================"
            uv run "$file"
          done
