name: Run Worker Script

on:
  workflow_dispatch:

env:
    PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
    PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}

jobs:
  run-worker:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install deps and run worker
      run: |
        python -m pip install --upgrade pip uv
        uv venv
        uv pip install -U prefect-docker --pre
        python scripts/run_worker_for_a_bit.py
  