name: Conditional Workflow

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [test1, test2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate a test
        id: maybe_fail
        run: exit 1

      - name: Create failure flag
        if: ${{ failure() }}
        run: echo "Failure in ${{ matrix.test }}" > "${{ matrix.test }}-failure.txt"

      - name: Upload failure flag
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.test }}-failure-flag"
          path: "${{ matrix.test }}-failure.txt"

  notify-tests-failing-on-main:
    needs: run-tests
    if: github.ref == 'refs/heads/main' && failure()
    runs-on: ubuntu-latest
    steps:
      - name: Download all failure flags
        uses: actions/download-artifact@v2
        with:
          path: failure-flags/

      - name: Check for failure flags and print their content
        id: check_failure
        run: |
          ls -al failure-flags/*  # List directory to debug
          failure_count=$(ls -1q failure-flags/*/*.txt | wc -l)
          failed_tests=$(basename -a failure-flags/*/*.txt | tr '\n' ', ')
          
          echo "Failure Count: $failure_count"  # Debug print
          echo "Failed Tests: $failed_tests"  # Debug print
          
          if [ $failure_count -gt 3 ]; then
            tests_failed="true"
          else
            tests_failed="false"
          fi
          echo "tests_failed=$tests_failed" >> $GITHUB_ENV  # Make it an env var
          echo "tests_failed=$tests_failed" >> $GITHUB_OUTPUT  # Set output variable

      - name: Failure Notification
        if: steps.check_failure.outputs.tests_failed == 'true'
        run: |
          echo "More than three tests failed. Sending notification."