name: Conditional Workflow

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [test1, test2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate a test
        id: maybe_fail
        run: exit 1

      - name: Create failure flag
        if: ${{ failure() }}
        run: echo "Failure in ${{ matrix.test }}" > "${{ matrix.test }}-failure.txt"

      - name: Upload failure flag
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.test }}-failure-flag"
          path: "${{ matrix.test }}-failure.txt"

  notify-tests-failing-on-main:
    needs: run-tests
    if: github.ref == 'refs/heads/main' && failure()
    runs-on: ubuntu-latest
    steps:
      - name: Download all failure flags
        uses: actions/download-artifact@v2
        with:
          path: failure-flags/

      - name: Check for failure flags and print their content
        id: check_failure
        run: |
          for flag in failure-flags/*/*.txt; do
            if [ -f "$flag" ]; then
              echo "TESTS_FAILED=true" >> $GITHUB_ENV
              echo "Contents of $flag:"
              cat "$flag"
            fi
          done
          if [ -z "$TESTS_FAILED" ]; then
            echo "TESTS_FAILED=false" >> $GITHUB_ENV
          fi

      - name: Failure Notification
        if: env.TESTS_FAILED == 'true'
        run: echo "Tests have failed."
        